services:
  app:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    volumes:
      - ./app:/app
    expose:
      - "8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASS}
      DATABASE_NAME: ${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - app/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - app/.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    logging:
      options:
        max-size: 10m

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - app
    restart: unless-stopped

#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    command: certonly --webroot -w /var/www/certbot --force-renewal --email krasikokirill@yandex.ru -d chess.alavenir.digital --agree-tos --non-interactive
#    logging:
#      options:
#        max-size: 10m


volumes:
  postgres_data:
  pgadmin_data:
